# Generated by Django 4.2.7 on 2026-02-14 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0003_programfee"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tuitionpayment",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tuition_payments",
                to="university.level",
                verbose_name="Niveau",
            ),
        ),
        migrations.AddField(
            model_name="tuitionpayment",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tuition_payments",
                to="university.semester",
                verbose_name="Semestre",
            ),
        ),
    ]
