# Generated by Django 5.2.11 on 2026-02-23 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_tuitionpayment_level_tuitionpayment_semester"),
        ("university", "0003_programfee"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tuitionfee",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tuitionfee",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tuition_fees",
                to="university.level",
                verbose_name="Niveau",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tuitionfee",
            unique_together={("program", "academic_year", "level")},
        ),
    ]
