# Generated by Django 4.2.7 on 2026-02-14 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0002_alter_program_options_remove_program_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_fees",
                        to="university.academicyear",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="university.level",
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="university.program",
                        verbose_name="Programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frais de programme",
                "verbose_name_plural": "Frais de programmes",
                "unique_together": {("program", "level", "academic_year")},
            },
        ),
    ]
